---

# Default timeout for each task
timeout_in: 60m

aws_credentials: ENCRYPTED[4ca070bffe28eb9b27d63c568b52970dd46f119c3a83b8e443241e895dbf1737580b4d84eed27a311a2b74287ef9f79f]

m1_mac_test_task:
    # https://cirrus-ci.org/guide/persistent-workers/
    persistent_worker:
      labels:
        name: MacM1-2
        arch: arm64
    env:
      CIRRUS_SHELL: "/bin/bash"  # sh is the default
      # go complains if this is under /tmp or /private/tmp/ (cirrus default)
      CIRRUS_WORKING_DIR: "$HOME/cirrus-task-${CIRRUS_TASK_ID}"
      TMPDIR: "$HOME"  # TODO: This is weird, no user would ever do this, but e2e readme says to do it :S
      # Consumed by podman-machine ginkgo tests
      CONTAINERS_MACHINE_PROVIDER: "applehv"
      # TODO: Should not require a special image, for now it does.
      MACHINE_IMAGE: "https://fedorapeople.org/groups/podman/testing/applehv/arm64/fedora-coreos-38.20230925.dev.0-applehv.aarch64.raw.gz"
      # TODO: Should be in makefile
      GINKGO_TAGS: "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp remote"
    # TODO: How long should we wait if things go badly?
    timeout_in: 20m
    # Requires pre-installed: go go-md2man coreutils vfkit from brew
    setup_script:
      # FIXME: Task runs as same user servicing pool!  There should be some filesystem-level
      # isolation between successive tasks to prevent collisions and simplify cleanup.
      - echo "PATH=$PATH:$CIRRUS_WORKING_DIR/bin/darwin" >> $CIRRUS_ENV
      - mkdir -p "$TMPDIR"
      # Default containers.conf helper_binaries_dir only searches global paths
      - mkdir -p $HOME/.config/containers
      - |
        cat << EOF > $HOME/.config/containers/containers.conf
        [engine]
        helper_binaries_dir=[
          "$CIRRUS_WORKING_DIR/bin/darwin",
          "/usr/local/opt/podman/libexec",
          "/opt/homebrew/bin",
          "/opt/homebrew/opt/podman/libexec",
          "/usr/local/bin",
          "/usr/local/libexec/podman",
          "/usr/local/lib/podman",
          "/usr/libexec/podman",
          "/usr/lib/podman"
        ]
        EOF
    info_script:
      - id
      - pwd
      - printenv
    build_script:
      - go version
      - go env
      - make .install.ginkgo
      - make podman-remote
      - make podman-mac-helper
      # Required version may change from one task to the next
      - make darwin-gvproxy
    smoke_script:
      - vfkit --version
      - |
        ./bin/darwin/podman --log-level=debug machine init --image-path $MACHINE_IMAGE --now;
        ./bin/darwin/podman run -i --rm quay.io/libpod/alpine:latest echo HelloWorld;
        ./bin/darwin/podman --log-level=debug machine rm --force || true;
        ps wx;
      - ./bin/darwin/podman --log-level=debug system reset --force || true
    e2e_script:
      # TODO: Can this please be a make target?
      - ./test/tools/build/ginkgo -vv --tags "$GINKGO_TAGS" -timeout=90m --trace --no-color --focus-file "basic_test.go" pkg/machine/e2e/.
    always:
      # Try to prevent one task from influencing another
      # Assumes worker-user runs one task at a time!
      task_cleanup_script:
        - killall podman || true
        - killall vfkit || true
        - killall gvproxy || true
        - rm -rf $HOME/.??* $HOME/*
        - rm -f /private/tmp/*${CIRRUS_TASK_ID}*
        # TODO: Cirrus agent or pool worker isn't cleaning up it's own tmp scripts
        - rm -f /private/tmp/scripts*.sh
